ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS fiscal_fd TEXT,
  ADD COLUMN IF NOT EXISTS fiscal_fn TEXT,
  ADD COLUMN IF NOT EXISTS fiscal_fp TEXT,
  ADD COLUMN IF NOT EXISTS fiscal_kkt_reg TEXT,
  ADD COLUMN IF NOT EXISTS fiscal_date TIMESTAMPTZ;
