ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS discount_percent NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_money NUMERIC(12,2) DEFAULT 0;

ALTER TABLE order_items
  ADD COLUMN IF NOT EXISTS discount_percent NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_money NUMERIC(12,2) DEFAULT 0;
