"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { DashboardData, DashboardUnpaidVisit } from "@/lib/api/dashboard";

type Mode = "unpaid" | "expiring" | "stock" | null;

export function AttentionPanelLive({ data }: { data: DashboardData["attention"] }) {
  const [mode, setMode] = useState<Mode>(null);
  const unpaidGroups = useMemo(() => groupUnpaidVisits(data.unpaid_visits), [data.unpaid_visits]);
  const total = data.unpaid_visits.length + data.expiring_subscriptions.length + data.low_stock.length;
  const controls = [
    { mode: "unpaid" as const, count: data.unpaid_visits.length, label: "Посещения к оплате", color: "text-[#ff9d73]" },
    { mode: "expiring" as const, count: data.expiring_subscriptions.length, label: "Абонементы истекают сегодня", color: "text-[#ffc45c]" },
    { mode: "stock" as const, count: data.low_stock.length, label: "Товары ниже минимума", color: "text-[#9093ff]" },
  ].filter((item) => item.count > 0);

  return <>
    <aside className="self-start rounded-[24px] border border-white/[.08] bg-[rgba(17,23,34,.72)] p-5 shadow-[0_24px_70px_rgba(0,0,0,.14)]">
      <div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-[.24em] text-[#7e899d]">Контроль</p><h2 className="mt-2 text-xl font-semibold text-[#edf1f6]">Требует внимания</h2></div>{total > 0 && <strong className="text-xl font-semibold text-[#ffc45c]">{total}</strong>}</div>
      {controls.length > 0 ? <div className="mt-5 space-y-2">{controls.map((item) => <button key={item.mode} type="button" onClick={() => setMode(item.mode)} className="group grid w-full grid-cols-[28px_minmax(0,1fr)_18px] items-center gap-2 rounded-[15px] px-3 py-3 text-left transition hover:bg-[#5ef4d8]/10"><strong className={`text-base ${item.color}`}>{item.count}</strong><span className="text-sm leading-5 text-[#cfd5df]">{item.label}</span><span className="text-[#667286] transition group-hover:translate-x-0.5 group-hover:text-[#c3cad5]"><ArrowRightIcon /></span></button>)}</div> : <p className="mt-6 rounded-[15px] bg-[#5ef4d8]/[.055] px-4 py-5 text-sm text-[#8fa49f]">Сейчас нет задач, требующих внимания.</p>}
    </aside>
    {mode && <div className="fixed inset-0 z-[100] flex justify-end bg-[#03060b]/65 backdrop-blur-[3px]" onMouseDown={() => setMode(null)}><section className="h-full w-full max-w-[520px] overflow-y-auto border-l border-white/[.08] bg-[#0d131d] p-5 shadow-[-30px_0_90px_rgba(0,0,0,.45)] sm:p-7" onMouseDown={(event) => event.stopPropagation()}><button type="button" onClick={() => setMode(null)} className="float-right grid h-9 w-9 place-items-center rounded-xl bg-white/[.05] text-[#9aa4b5] hover:text-white" title="Закрыть">×</button>{mode === "unpaid" && <UnpaidContent groups={unpaidGroups} />}{mode === "expiring" && <ExpiringContent items={data.expiring_subscriptions} />}{mode === "stock" && <StockContent items={data.low_stock} />}</section></div>}
  </>;
}

function Heading({ eyebrow, title, text, color }: { eyebrow: string; title: string; text: string; color: string }) { return <header className="pr-12"><p className={`text-[10px] uppercase tracking-[.24em] ${color}`}>{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold text-[#edf1f6]">{title}</h2><p className="mt-2 text-sm leading-6 text-[#778296]">{text}</p></header>; }

function UnpaidContent({ groups }: { groups: ReturnType<typeof groupUnpaidVisits> }) { return <><Heading eyebrow="Посещения к оплате" title={`${groups.length} клиентов · ${groups.reduce((sum, group) => sum + group.visits.length, 0)} занятий`} text="Только посещения с подтверждённым приходом." color="text-[#ff9d73]" /><div className="mt-7 space-y-3">{groups.map((group) => <article key={group.clientId} className="rounded-[20px] border border-white/[.08] bg-white/[.025] p-5"><div className="flex items-center justify-between gap-4"><h3 className="font-semibold text-[#e5eaf1]">{group.clientName}</h3><span className="text-xs text-[#ffad87]">{group.visits.length} к оплате</span></div><div className="mt-3 divide-y divide-white/[.06]">{group.visits.map((visit) => <div key={visit.id} className="grid grid-cols-[78px_minmax(0,1fr)_48px] gap-2 py-3 text-sm"><span className="text-xs text-[#7f8a9d]">{formatDate(visit.visit_date)}</span><span className="text-[#d5dbe4]">{visit.title}</span><span className="text-right text-xs text-[#9da7b8]">{String(visit.visit_time).slice(0, 5)}</span></div>)}</div><Link href={`/sales?client_id=${group.clientId}`} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-[#5ef4d8]/10 px-3 py-2 text-xs font-medium text-[#5ef4d8]">Перейти к продаже <ArrowRightIcon /></Link></article>)}</div></>; }

function ExpiringContent({ items }: { items: DashboardData["attention"]["expiring_subscriptions"] }) { return <><Heading eyebrow="Истекают сегодня" title={`${items.length} абонементов`} text="Клиенты, которым можно предложить продление." color="text-[#ffc45c]" /><div className="mt-7 space-y-3">{items.map((item) => <article key={item.id} className="rounded-[20px] border border-white/[.08] bg-white/[.025] p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold text-[#e5eaf1]">{item.client_name}</h3><p className="mt-1 text-sm text-[#8a95a7]">{item.product_name || item.type}</p></div>{item.visits_left !== null && <strong className="text-xl text-[#ffc45c]">{item.visits_left}</strong>}</div><div className="mt-4 flex justify-end border-t border-white/[.06] pt-4"><Link href={`/sales?client_id=${item.client_id}`} className="group inline-flex items-center gap-2 rounded-xl bg-[#ffc45c]/10 px-3 py-2 text-xs font-medium text-[#ffd27b]">Продлить <span className="transition-transform group-hover:translate-x-0.5"><ArrowRightIcon /></span></Link></div></article>)}</div></>; }

function StockContent({ items }: { items: DashboardData["attention"]["low_stock"] }) { return <><Heading eyebrow="Минимальный остаток" title={`${items.length} позиций нужно пополнить`} text="Фактические остатки склада ниже установленного минимума." color="text-[#a7a9ff]" /><div className="mt-7 overflow-hidden rounded-[20px] border border-white/[.08] bg-white/[.025]">{items.map((item) => <div key={item.id} className="grid grid-cols-[minmax(0,1fr)_64px_72px] items-center gap-3 border-b border-white/[.06] px-4 py-4 last:border-0"><div><p className="text-sm font-medium text-[#dce2eb]">{item.name}</p><p className="mt-1 text-xs text-[#6f7a8e]">Минимум: {item.min_stock}</p></div><div className="text-right"><p className="text-[10px] uppercase text-[#667286]">Осталось</p><strong className="text-base text-[#ff9d73]">{item.stock}</strong></div><div className="text-right"><p className="text-[10px] uppercase text-[#667286]">Добавить</p><strong className="text-base text-[#a7a9ff]">+{item.shortage}</strong></div></div>)}</div><Link href="/warehouse" className="mt-4 inline-flex items-center gap-2 rounded-[14px] bg-[#9093ff] px-4 py-3 text-sm font-semibold text-[#0a0c16]">Открыть склад <ArrowRightIcon /></Link></>; }

function groupUnpaidVisits(visits: DashboardUnpaidVisit[]) { const groups = new Map<string, { clientId: string; clientName: string; visits: DashboardUnpaidVisit[] }>(); for (const visit of visits) { const key = String(visit.client_id); const group = groups.get(key) ?? { clientId: key, clientName: visit.client_name, visits: [] }; group.visits.push(visit); groups.set(key, group); } return [...groups.values()]; }
function formatDate(value: string) { const date = new Date(`${String(value).slice(0, 10)}T00:00:00`); return new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "short" }).format(date); }
function ArrowRightIcon() { return <svg viewBox="0 0 18 18" width="18" height="18" fill="none" aria-hidden="true"><path d="M3.5 9h10M9.5 5l4 4-4 4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
